name: Main Workflow
on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  packages: write
  attestations: write
  
jobs:
  Build_Docker:
    uses: ./.github/workflows/docker-build.yaml
