name: Main Workflow
on:
  release:
    types: [published]
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write
  packages: write
  attestations: write
  
jobs:
  Build_Docker:
    uses: ./.github/workflows/docker-build.yaml

  Build_Linux_binaries:
    uses: ./.github/workflows/ubuntu.yml
    secrets: inherit
    
  Build_MacOS_binaries:
    uses: ./.github/workflows/macos-build.yml
    secrets: inherit
  
  Build_Windows_binaries:
    uses: ./.github/workflows/windows.yml
    secrets: inherit
  
  Build_openapi:
    uses: ./.github/workflows/build.yaml
